name: "mymusicflow"
id: "212422"
secretKey: "5fd674526716689e817431e34e7ac214"
domain: "mymusicflow.me"
redirectUrl: "https://mymusicflow.me/deezer/connected"
connectUrl: "https://connect.deezer.com/oauth/auth.php?perms=PERMISSIONS&format=window&app_id=YOUR_APP_ID&redirect_uri=YOUR_REDIRECT_URI"